# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 05:23
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
